name: firebase_ui
description: Firebase auth UI, dart package to mimic the firebaseUI(Google, Facebook, Email supported)
version: 1.0.12
homepage: https://github.com/Maliffic/firebase_ui

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  crypto: ^3.0.0
  device_info: ^2.0.0
  firebase_auth: ^4.2.3
  google_sign_in: ^6.1.5
  http: ^1.0.0
  # flutter_facebook_login: ^3.0.0
  sn_progress_dialog: ^1.0.3
  sign_in_with_apple: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

dependency_overrides:
  # intl: ^0.17.0

flutter:
  assets:
    - assets/email-logo.png
    - assets/2.0x/email-logo.png
    - assets/3.0x/email-logo.png

    - assets/go-logo.png
    - assets/2.0x/go-logo.png
    - assets/3.0x/go-logo.png

    - assets/apple.png
