name: firebase_ui
description: Firebase auth UI, dart package to mimic the firebaseUI(Google, Email supported)
version: 2.0.0
homepage: https://github.com/SoftWyer/firebase_ui

environment:
  sdk: '>=3.11.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  crypto: ^3.0.0
  device_info_plus: ^12.0.0
  firebase_auth: ^6.3.0
  google_sign_in: ^7.2.0
  http: ^1.0.0
  sn_progress_dialog: ^1.0.3
  sign_in_with_apple: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

dependency_overrides:
  # intl: ^0.17.0

flutter:
  assets:
    - assets/email-logo.png
    - assets/2.0x/email-logo.png
    - assets/3.0x/email-logo.png

    - assets/go-logo.png
    - assets/2.0x/go-logo.png
    - assets/3.0x/go-logo.png

    - assets/apple.png
