name: firebase_ui
description: Firebase auth UI, dart package to mimic the firebaseUI(Google, Facebook, Email supported)
version: 1.0.10
homepage: https://github.com/Maliffic/firebase_ui

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  crypto: ^3.0.0
  device_info: ^2.0.0
  firebase_auth: ^3.0.1
  google_sign_in: ^5.0.0
  http: ^0.13.0
  # flutter_facebook_login: ^3.0.0
  sn_progress_dialog: ^1.0.3
  sign_in_with_apple: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

dependency_overrides:
  # intl: ^0.17.0

flutter:
  assets:
    - assets/email-logo.png
    - assets/2.0x/email-logo.png
    - assets/3.0x/email-logo.png

    - assets/go-logo.png
    - assets/2.0x/go-logo.png
    - assets/3.0x/go-logo.png

    - assets/apple.png
